services:
  db:
    image: postgres:latest
    container_name: my-postgres
    # restart: always
    environment:
      POSTGRES_USER: crzy
      # POSTGRES_PASSWORD: postgrespw123
      POSTGRES_PASSWORD_FILE: "/run/secrets/postgres-password"
      POSTGRES_DB: crzy-fs-db
    ports:
      - 5432:5432 # local:docker
    volumes:
      - crzy-fs-db-data:/var/lib/postgresql/data
      - ./.db_password:/run/secrets/postgres-password:ro

  adminer:
    image: adminer
    # restart: always
    ports:
      - 8088:8080

volumes:
  crzy-fs-db-data:
